### PR TITLE
Introduced remove format feature

### LINKED ISSUE #908: Consider implementing a v4-like remove format feature
## Is this a bug report or feature request? (choose one)

 🆕 Feature request

## 📃 Other details that might be useful

This feature, similar to https://ckeditor.com/cke4/addon/removeformat could be useful when working with huge chunks of text containing unwanted formatting (mostly basic styles, links, etc.). A simple use case could be pasting a section of a Wikipedia article.

image

Some members of the community asked us about this feature a couple of times already.

(somehow) related issues:
* https://github.com/ckeditor/ckeditor5-link/issues/149
* https://github.com/ckeditor/ckeditor5-highlight/issues/16

cc @Reinmar @wwalc

### PR DESCRIPTION
**Pull request by mlewand**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature: Introduced the remove format feature. Closes ckeditor/ckeditor5#908.

---

### Additional information

* For now there are following dependencies:
	* ~~core should be at branch: [`t/ckeditor5/1457`](https://github.com/ckeditor/ckeditor5-core/tree/t/ckeditor5/1457) (to fetch the icon)~~
	* the root repo should be at branch: [`t/ckeditor5/908`](https://github.com/ckeditor/ckeditor5/tree/t/ckeditor5/908) (to include the package in mgit.json)
* Based on discussion in ckeditor/ckeditor5#908 there is a need for handling properties in the schema. For now this PR implements a simplified approach, with preconfigured (hardcoded) array of known format options. As the upstream issue is fixed, we'll implement it in remove format.

### CODE REVIEW

**Review by oleq — CHANGES_REQUESTED** [review]
I pushed some corrections to the API docs, the guide, etc..

I found two issues so far:
1. (must be addressed) There's an error thrown in a certain situation with the highlight 
Kapture 2019-03-29 at 13 35 09

2. (could be a follow-up) The command is not enabled if an entire block with text alignment is selected #6

**Comment by oleq** [comment]
As for 1. my guess is that it happens when a text has more than 1 attribute (any attribute).

When `writer.removeAttribute( attrA, item )` is called, `item` no longer makes sense when `writer.removeAttribute( attrB, item )` is called. `item` is outdated. It looks like this helps:

```diff
diff --git a/src/removeformatcommand.js b/src/removeformatcommand.js
index 77278a2..9c62492 100644
--- a/src/removeformatcommand.js
+++ b/src/removeformatcommand.js
@@ -52,11 +52,15 @@ export default class RemoveFormatCommand extends Command {

                   model.change( writer => {
                            for ( const item of this._getStylableElements( model.document.selection ) ) {
-                                    for ( const attributeName of removableAttributes ) {
-                                             if ( item instanceof DocumentSelection ) {
+                                    if ( item.is( 'selection' ) ) {
+                                             for ( const attributeName of removableAttributes ) {
                                                       writer.removeSelectionAttribute( attributeName );
-                                             } else {
-                                                      writer.removeAttribute( attributeName, item );
+                                             }
+                                    } else {
+                                             const itemRange = writer.createRangeOn( item );
+
+                                             for ( const attributeName of removableAttributes ) {
+                                                      writer.removeAttribute( attributeName, itemRange );
                                              }
                                     }
                            }
```

P.S. `is()` instead of `instanceof`.

**Comment by oleq** [comment]
An afterthought: why do we need `_getStylableElements` in the first place? Wouldn't it be easier if we did that:

```js
const range = model.document.selection.getFirstRange();

for ( const attributeName of removableAttributes ) {
     writer.removeAttribute( attributeName, range );
}
```

**Comment by mlewand** [comment]
I have updated `t/ckeditor5/908` branch.

* Your assumptions in https://github.com/ckeditor/ckeditor5-remove-format/pull/1#issuecomment-478023646 were correct, the issue was caused by implicitly merged textnodes (I'll report an issue for that as it is unexpected behavior, but pretty tricky to fix).
	* Covered this case with an integration test.
* I have integrated the feature with `isFormatting` attribute property, so that it works on schema rather than predefined attr list.
	* This resulted with introducing `_getFormattingAttributes` method. Because of that I have renamed to `_getFormattedElements` in order to use "format" consistently rather than "style".
* Removed highlight plugin from manual test, as it is no longer removed by the remove format feature.

There are [2 known tests failing](https://github.com/ckeditor/ckeditor5-mention/issues/12).

As for:

> An afterthought: why do we need `_getStylableElements` in the first place? Wouldn't it be easier if we did that:

That was my initial attempt, however it turned out it won't remove styles in nested editables (e.g. image caption). So I ended up handling this manually and putting this into a generator, so that both `execute()` and `refresh()` can reuse same logic.

**Pull request merged**
